---
- name: Install Jenkins on EC2
  hosts: ec2_servers
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Update package cache (RHEL/CentOS/Amazon Linux)
      yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

  roles:
    - jenkins

  post_tasks:
    - name: Display Jenkins installation summary
      debug:
        msg: |
          ========================================
          JENKINS INSTALLATION COMPLETE!
          ========================================
          
          Jenkins version: {{ jenkins_version }}
          Jenkins port: {{ jenkins_port }}
          
          Access URL: http://{{ ansible_default_ipv4.address }}:{{ jenkins_port }}
          
          Default credentials:
          - Username: {{ jenkins_admin_user }}
          - Password: {{ jenkins_admin_password }}
          
          Jenkins service is running and enabled.
          
          ========================================

    - name: Show Jenkins initial admin password
      shell: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password
      changed_when: false
      failed_when: false

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_initial_password.stdout }}"
      when: jenkins_initial_password.stdout != ""

# ========================================
# JENKINS LTS INSTALLATION PLAYBOOK
# ========================================
#
# This playbook installs Jenkins LTS (Long Term Support) with complete configuration.
# Jenkins is a popular CI/CD automation server for building, testing, and deploying.
#
# USAGE:
#   ansible-playbook playbooks/jenkins.yml
#
# WHAT GETS INSTALLED:
#   1. Jenkins LTS from official repository
#   2. Java 17 (required for Jenkins)
#   3. Jenkins configuration files
#   4. Systemd service configuration
#   5. Initial admin password retrieval
#
# FEATURES:
#   - LTS version for stability
#   - Custom port configuration (default: 8080)
#   - Java options optimization
#   - Log rotation configuration
#   - Service auto-start and enable
#   - Jenkins user added to docker group
#
# ACCESS:
#   - URL: http://YOUR_EC2_IP:8080
#   - Username: admin
#   - Password: (shown in playbook output)
#
# PORTS:
#   - Jenkins: 8080 (configurable)
#
# VERIFICATION:
#   - sudo systemctl status jenkins
#   - curl http://localhost:8080
#   - sudo journalctl -u jenkins
#
# TROUBLESHOOTING:
#   - If service fails: Check Java installation
#   - If port issues: Verify port 8080 is open
#   - If password not shown: Check /var/lib/jenkins/secrets/
#   - If startup slow: Check system resources
#
# ========================================
