---
- name: Install Kubernetes Tools on EC2
  hosts: ec2_servers
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Update package cache (RHEL/CentOS/Amazon Linux)
      yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

  roles:
    - kubernetes_tools

  post_tasks:
    - name: Display Kubernetes tools installation summary
      debug:
        msg: |
          ========================================
          KUBERNETES TOOLS INSTALLATION COMPLETE!
          ========================================
          
          Tools installed:
          - AWS CLI v2
          - kubectl
          - eksctl
          - Helm
          
          Bash completion configured for:
          - kubectl (alias: k)
          - eksctl (alias: e)
          - helm (alias: h)
          
          Test commands:
          - aws --version
          - kubectl version --client
          - eksctl version
          - helm version
          
          Next steps:
          1. Configure AWS credentials: aws configure
          2. Set up kubectl context for your cluster
          3. Configure Helm repositories
          4. Start using eksctl to create/manage EKS clusters
          
          ========================================

# ========================================
# KUBERNETES TOOLS INSTALLATION PLAYBOOK
# ========================================
#
# This playbook installs essential Kubernetes and AWS tools for container
# orchestration and cloud management.
#
# USAGE:
#   ansible-playbook playbooks/kubernetes_tools.yml
#
# WHAT GETS INSTALLED:
#   1. AWS CLI v2 (latest version)
#   2. kubectl (Kubernetes command-line tool)
#   3. eksctl (Amazon EKS CLI tool)
#   4. Helm (Kubernetes package manager)
#   5. Bash completion for all tools
#
# TOOLS OVERVIEW:
#   - AWS CLI: Command-line interface for AWS services
#   - kubectl: Manage Kubernetes clusters and resources
#   - eksctl: Create and manage Amazon EKS clusters
#   - Helm: Install and manage Kubernetes applications
#
# FEATURES:
#   - Latest versions of all tools
#   - Bash completion and aliases
#   - Multi-distribution support
#   - Proper GPG key verification
#   - System integration
#
# ALIASES CONFIGURED:
#   - k = kubectl
#   - e = eksctl
#   - h = helm
#
# VERIFICATION:
#   - aws --version
#   - kubectl version --client
#   - eksctl version
#   - helm version
#
# CONFIGURATION:
#   - AWS: aws configure
#   - kubectl: kubectl config set-cluster
#   - eksctl: eksctl create cluster
#   - Helm: helm repo add
#
# TROUBLESHOOTING:
#   - If AWS CLI fails: Check internet connectivity
#   - If kubectl fails: Verify Kubernetes cluster access
#   - If eksctl fails: Check AWS credentials
#   - If Helm fails: Verify repository configuration
#
# ========================================
